### ISSUE TITLE
AttributeError: 'Medical3D' object has no attribute 'getLabel'

### ISSUE THREAD

**Issue by 11710615** [NarcissusEx/CuNeRF#6]
It seems 'Medical3D' object has no attribute 'getLabel'.
I wonder if some codes are not uploaded?

**Comment by NarcissusEx** [comment]
thanks for your attention. We fixed this bug 3 weeks ago. Please see https://github.com/NarcissusEx/CuNeRF/commit/9da7b0cdaf5a223ae4dbee205f3c4c7da1f2b6f6#r141911660
